# catch
To handle this issue we have another method as `.catch()` . This is nothing but a syntactical sugar for `.then()` . In case of error at anytime between the chain the call will be directed to the immediate `.catch()` .

#catch #promises #async